# Generated by Django 4.2 on 2023-05-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=60, unique=True)),
                ('nome_empresa', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('quantidade_acoes', models.IntegerField()),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('corretagem', models.FloatField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.stock')),
            ],
        ),
    ]
