# Generated by Django 4.2 on 2023-05-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0003_transaction_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Preco',
            new_name='preco',
        ),
    ]
